server:
  port: ${PORT:80}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false


logging:
  level:
    org:
      atmosphere: warn
    com.example.application: debug


config:
  doc-split:
    enable: true
    repo-path: /home/tian/doc-util/htc-document

# To improve the performance during development. 
# For more information https://vaadin.com/docs/v14/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
