# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  workflow_dispatch:
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and run
      run: |
        mvn vaadin:build-frontend
        mvn package -Pproduction
        mvn spring-boot:run -Dvaadin.productionMode=true
      
      
