# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to dev

on:
  push:
    branches: [ master ]
  workflow_dispatch:
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "1234"
          host: 18.177.82.195
          user: ec2-user
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          args: "-tt -vvv"

      




















